function plots( trc, swl, swr )
% sw = read_sw(raw)   
% 
%     This function is ...
% 
%     INPUTS:
%         trc = [1, 1] = Makers Position
%         swl = [1, 1] = SmarWheel Data - left
%         swr = [1, 1] = SmarWheel Data - right

    
    %% Plot Forces-left x Sample
	figure(1);
       
    subplot(411); hold on
    plot(swl.Sn, swl.Fx,...
        'LineWidth', 2,...
        'Color', 'b');
    plot(swr.Sn, swr.Fx,...
        'LineWidth', 2,...
        'Color', 'r');  
    ylabel('Fx [N])');
    title('Forces applied in the left wheel')
                   
    subplot(412); hold on
    plot(swl.Sn, swl.Fy,...
        'LineWidth', 2,...
        'Color', 'b');
    plot(swr.Sn, swr.Fy,...
        'LineWidth', 2,...
        'Color', 'r');  
    ylabel('Fy [N])');
    
    subplot(413); hold on
    plot(swl.Sn, swl.Fz,...
        'LineWidth', 2,...
        'Color', 'b');
    plot(swr.Sn, swr.Fz,...
        'LineWidth', 2,...
        'Color', 'r');  
    ylabel('Fz [N])');
    
    subplot(414); hold on
    plot(swl.Sn, sqrt(swl.Fx.*swl.Fx + swl.Fy.*swl.Fy + swl.Fz.*swl.Fz),...
        'LineWidth', 2,...
        'Color', 'b');
    plot(swr.Sn, sqrt(swr.Fx.*swr.Fx + swr.Fy.*swr.Fy + swr.Fz.*swr.Fz),...
        'LineWidth', 2,...
        'Color', 'r');    
    ylabel('Fr [N])');
    xlabel('Sample Number')
      
    
    %% Plot Moments-left x Sample
	figure(2);
       
    subplot(411); hold on
    plot(swl.Sn, swl.Mx,...
        'LineWidth', 2,...
        'Color', 'b');
    plot(swr.Sn, swr.Mx,...
        'LineWidth', 2,...
        'Color', 'r');      
    ylabel('Mx [Nm])');
    title('Moments applied in the left wheel')
                   
    subplot(412); hold on
    plot(swl.Sn, swl.My,...
        'LineWidth', 2,...
        'Color', 'b');
    plot(swr.Sn, swr.My,...
        'LineWidth', 2,...
        'Color', 'r');    
    ylabel('My [Nm])');
    
    subplot(413); hold on
    plot(swl.Sn, swl.Mz,...
        'LineWidth', 2,...
        'Color', 'b');
    plot(swr.Sn, swr.Mz,...
        'LineWidth', 2,...
        'Color', 'r');      
    ylabel('Mz [Nm])');
    
    subplot(414); hold on
    plot(swl.Sn, sqrt(swl.Mx.*swl.Mx + swl.My.*swl.My + swl.Mz.*swl.Mz),...
        'LineWidth', 2,...
        'Color', 'b');
    plot(swr.Sn, sqrt(swr.Mx.*swr.Mx + swr.My.*swr.My + swr.Mz.*swr.Mz),...
        'LineWidth', 2,...
        'Color', 'r');    
    ylabel('Mr [Nm])');
    xlabel('Sample Number') 
end

